name: Release Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd JobTrip_Extention
          npm ci
        
      - name: Build extension
        run: |
          cd JobTrip_Extention
          npm run build
        
      - name: Create ZIP file
        run: |
          cd JobTrip_Extention/dist || exit
          zip -r ../../jobtrip-extension-${{ github.ref_name }}.zip *
          cd ../..
          
      - name: Extract manifest version
        id: manifest
        run: |
          VERSION=$(node -p "require('./JobTrip_Extention/manifest.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: jobtrip-extension-${{ github.ref_name }}.zip
          name: JobTrip Extension v${{ steps.manifest.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true 